import type { DecisionResult, OfferInput, VehicleProfile } from "@/types/decision";

export const defaultVehicle: VehicleProfile = {
  id: "golf-7",
  name: "VW Golf 7",
  fuelType: "DIESEL",
  consumptionPer100Km: 5.2,
  fuelPricePerUnit: 1.89,
  cargoVolumeLiters: 380,
  maxPayloadKg: 400,
};

export const defaultOfferInput: OfferInput = {
  url: "https://www.kleinanzeigen.de/s-anzeige/kommode-hamburg-123456789",
  productName: "Kommode",
  originalPrice: 790,
  askingPrice: 80,
  homeLocation: "Münster",
  sellerLocation: "Hamburg",
  vehicle: defaultVehicle,
  timeValuePerHour: 15,
  includeTimeCosts: true,
};

export const mockDecision: DecisionResult = {
  id: "decision-001",
  status: "LOHNT_SICH",
  headline: "🟢 KAUF LOHNT SICH",
  dealScore: 87,
  originalPrice: 790,
  currentMarketRange: { min: 250, max: 350 },
  askingPrice: 80,
  transportCost: 232.17,
  transportMode: "Miettransporter Carlos XL",
  effectivePurchasePrice: 312.17,
  effectiveSavings: 477.83,
  savingsAgainstCurrentMarket: 170,
  distanceKm: 282,
  roundTripDistanceKm: 564,
  drivingTimeMinutes: 346,
  timeCost: 105,
  priceAdvantage: 710,
  effectiveFinancialAdvantage: 478,
  advantageIncludingTime: 373,
  recommendation: "JA – trotz Entfernung wirtschaftlich",
  reasons: [
    "Originalprodukt war historisch 790 € und ist nicht mehr aktuell erhältlich.",
    "Kaufpreis beträgt nur 80 €.",
    "Effektiver Kaufpreis inklusive Transport liegt bei 312 €.",
    "Bei 564 km Gesamtstrecke bleibt der Deal für die persönliche Kalkulation weiterhin attraktiv.",
  ],
  warnings: [
    "564 km Gesamtstrecke",
    "ca. 6 Stunden reine Fahrzeit",
    "Zustand des gebrauchten Produkts muss vor Ort geprüft werden.",
  ],
  transportOptions: [
    {
      provider: "CarlundCarla",
      vehicleName: "Carlos XL",
      totalEstimatedCost: 232,
      distanceKm: 564,
      routeType: "Hin + Rückfahrt",
      notes: "Günstigster passender Transporter mit 11,3 m³ Ladevolumen",
      mode: "RENTAL",
    },
    {
      provider: "ADAC / Partner",
      vehicleName: "Transporter Standard",
      totalEstimatedCost: 245,
      distanceKm: 564,
      routeType: "Hin + Rückfahrt",
      notes: "Gutes Gesamtpaket, leicht höher als der günstigste Anbieter",
      mode: "RENTAL",
    },
    {
      provider: "SIXT",
      vehicleName: "Transporter One-Way",
      totalEstimatedCost: 268,
      distanceKm: 564,
      routeType: "One-Way",
      notes: "Praktisch, jedoch höheres Gesamtbudget",
      mode: "ONE_WAY_RENTAL",
    },
    {
      provider: "Eigenes Auto",
      vehicleName: "VW Golf 7",
      totalEstimatedCost: 144.3,
      distanceKm: 564,
      routeType: "Hin + Rückfahrt",
      notes: "Wenn das Möbelstück in den Golf passt, ist dies die günstigste private Option",
      mode: "OWN_CAR",
    },
  ],
};
